version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: greenpulse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: greenpulsedb
      MYSQL_USER: greenpulse
      MYSQL_PASSWORD: greenpulsepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

volumes:
  mysql_data:
