services:
  - type: web
    name: greenpulse-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontend-nine-woad-g8xvq6ys3s.vercel.app
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
